# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeorefExtension
                                 A QGIS plugin
 Extension to the Raster Georeferencer Plugin
 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-24
        copyright            : (C) 2020 by Christoph Candido
        email                : christoph.candido@gmx.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeorefExtension class from file GeorefExtension.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeorefExtension import GeorefExtension
    return GeorefExtension(iface)
